### ISSUE TITLE
Wrong GPIO listed for Filament Sensor 1

### ISSUE THREAD

**Issue by xanderphillips** [MotorDynamicsLab/LDOVoron01#10]
File has:
switch_pin: umb:gpio6

But if the wiring was done per the documentation to the E Stop on the SKR Pico board, the entry should be:
switch_pin: !gpio16

Found via the bigtreetech github for the SKR Pico board.

**Comment by cneshi** [comment]
Both pins are already listed in the config for you to choose because both the SKR Pico and Picobilical have filament sensor ports. Please see line 379 - 389 in printer.cfg
