### ISSUE TITLE
Documentation changes (Parts List)

### ISSUE THREAD

**Issue by JassMan23** [MotorDynamicsLab/LDOVoron01#5]
Instead of your documentation referring to 
LDO-1515-VRN200A , 
LDO-1515-VRN200B,
LDO-1515-VRN200C,
LDO-1515-VRN200D,
LDO-1515-VRN200E
why not call them 
LDO-1515-VRN200AB
LDO-1515-VRN200CH
LDO-1515-VRN200D etc then it will be obvious which ones align with the Voron documentation.

**Comment by camerony** [comment]
I think it's clearer the way it is. Thanks for the idea.
