### ISSUE TITLE
Documentation docs.ldomotors.com/en/voron/voron02/build-faqv02

### ISSUE THREAD

**Issue by JassMan23** [MotorDynamicsLab/LDOVoron01#6]
The above document says:
"PAGE 143 Use M3 lock nuts with the flat side up rather the the M3 hex nut and washer. We recommend
using an M3x30 or M3x35 screw for the Kirigami bed instead of the M3x40"

However it is virtually impossible to to install a lock nut backwards without stripping the nut or the screw since the nylon lock can not be guaranteed to cut a thread which is a continuation of the actual nut thread. Because of its resilience, the thread in the nylon recovers its smoothness before you are able to reverse it, if you thread it the normal way first.

A better solution is to use 2 hex (jam)nuts so the second locks against the first. 
Or providing something like this: ![](https://www.mecatechnic.com/img/photos/zoom/VI10056.jpg)

**Comment by camerony** [comment]
Thanks for the feedback.  We will consider that.
