### ISSUE TITLE
Power inlet needs to be resized

### ISSUE THREAD

**Issue by MrJohnson** [MotorDynamicsLab/LDOVoron01#7]
From the 0.2 R1 release notes:

"Skirts

We fixed the issue where 34mm Z motors didnt fit in the machine with the bottom panel installed, this involved increasing the height of the skirts/feet by 2mm
We added a simple filament runout sensor to the rear right foot"

The LDO-provided power inlet stl is now a different size than the official release and causes the printer to rock.

**Comment by cneshi** [comment]
There actually is an updated part for 0.2R1, you can find the part [here](https://github.com/MotorDynamicsLab/LDOVoron0/blob/v02r1/STLs/Power_Inlet/V02R1_Mains_Inlet%20Foot_1_2mm.stl) in the repo. That said, it seems the printed parts guide was not updated to point to this new part. I have rectified that issue. Thank you for the heads up
